apiVersion: v1
kind: Namespace
metadata:
  name: wt-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wutong-controller-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: wutong-controller-sa
    namespace: wt-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wutong-controller-sa
  namespace: wt-system
---    
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wutong-controller
  namespace: wt-system
spec:
  selector:
    matchLabels:
      app: wutong-controller
  template:
    metadata:
      labels:
        app: wutong-controller
    spec:
      containers:
      - name: controller
        image: swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-controller:v1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"